# Generated by Django 5.0.6 on 2026-05-16 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duree_minutes', models.PositiveIntegerField(default=30)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=False)),
                ('melange_questions', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_list', to='cours.cours')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField()),
                ('points', models.FloatField(default=1.0)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.cc')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='evaluations.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.DateTimeField(auto_now_add=True)),
                ('heure_soumission', models.DateTimeField(blank=True, null=True)),
                ('est_soumise', models.BooleanField(default=False)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.cc')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant')),
            ],
            options={
                'verbose_name': 'Tentative',
                'unique_together': {('etudiant', 'cc')},
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_brute', models.FloatField()),
                ('note_sur_20', models.FloatField()),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('receipt_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='evaluations.cc')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='accounts.etudiant')),
                ('tentative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluations.tentative')),
            ],
            options={
                'ordering': ['-date_validation'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix_selectionne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations.choix')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.question')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.tentative')),
            ],
            options={
                'unique_together': {('tentative', 'question')},
            },
        ),
    ]
