# Generated by Django 5.0.6 on 2026-05-16 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contenu_html', models.TextField(blank=True)),
                ('fichier_url', models.URLField(blank=True)),
                ('filiere', models.CharField(choices=[('TIC', 'TIC'), ('II', 'II'), ('TOUS', 'Tous')], default='TOUS', max_length=4)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_publie', models.BooleanField(default=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.enseignant')),
            ],
            options={
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_creation'],
            },
        ),
    ]
